<form class="form ask-question"
      action="<?= $block->escapeUrl($block->getUrl('ask_question/submit')) ?>"
      id="ask-question-form"
      method="post"
      data-mage-init='{"askQuestion":{}}'
      onsubmit="return false;"
>
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?= $block->escapeHtml(__('Ask your question.')) ?></span>
        </legend>
        <div class="field name required">
            <label class="label" for="name">
                <span><?= $block->escapeHtml(__('Name')) ?></span>
            </label>
            <div class="control">
                <input name="name"
                       id="name"
                       placeholder="<?= $block->escapeHtmlAttr(__('Your name')) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                       class="input-text" type="text"
                       data-validate="{required:true}"
                />
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email">
                <span><?= $block->escapeHtml(__('Email')) ?></span>
            </label>
            <div class="control">
                <input name="email"
                       id="email"
                       placeholder="<?= $block->escapeHtmlAttr(__('email@example.com')) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text"
                       type="email"
                       data-validate="{required:true, 'validate-email':true}"
                />
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone">
                <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
            </label>
            <div class="control">
                <input name="telephone"
                       id="telephone"
                       placeholder="<?= $block->escapeHtmlAttr(__('+380xxxxxxxxx')) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                       class="input-text"
                       type="text"
                       data-validate="{required:true, 'minlength':13, 'maxlength':13, 'validate-ua-phone-number':true}"
                />
            </div>
        </div>
        <div class="field question required">
            <label class="label" for="question">
                <span><?= $block->escapeHtml(__('Question')) ?></span>
            </label>
            <div class="control">
                        <textarea name="question"
                                  id="question"
                                  placeholder="<?= $block->escapeHtmlAttr(__('Input your question here')) ?>"
                                  title="<?= $block->escapeHtmlAttr(__('Question')) ?>"
                                  class="input-text"
                                  cols="5" rows="3"
                                  data-validate="{required:true}"
                        ></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value=""/>
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
